#!/usr/bin/env python3
"""Render the standalone district electoral-weight diagnostic.

The input is generated by the exact-audited Julia accounting pipeline. This
script validates the state-year rows, computes descriptive diagnostics, and
renders one point per state and election year without assigning states to
substantive categories.
"""

from __future__ import annotations

import argparse
from fractions import Fraction
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.ticker import FixedLocator, FixedFormatter, NullLocator
import numpy as np
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = (
    REPO_ROOT
    / "processing"
    / "Processing"
    / "output"
    / "paper"
    / "figure_data"
    / "accounting_district_electoral_weight.csv"
)
DEFAULT_OUTPUT = REPO_ROOT / "writing" / "figures" / "district_electoral_weight_by_magnitude.pdf"
DEFAULT_SUMMARY_OUTPUT = (
    REPO_ROOT
    / "processing"
    / "Processing"
    / "output"
    / "decomposition"
    / "diagnostics"
    / "district_electoral_weight_summary.csv"
)

EXPECTED_YEARS = (2014, 2018, 2022)
EXPECTED_NATIONAL_VALID_VOTES = {
    2014: 97_355_354,
    2018: 98_264_190,
    2022: 109_413_508,
}
EXPECTED_NATIONAL_SEATS = 513
EXPECTED_DISTRICTS = 27
REQUIRED_COLUMNS = {
    "election_year",
    "electoral_unit",
    "V_d",
    "S_d",
    "V",
    "S",
    "district_vote_share",
    "district_seat_share",
    "district_valid_votes_per_seat",
    "national_valid_votes_per_seat",
    "district_electoral_weight",
    "district_electoral_weight_exact",
}
INTEGER_COLUMNS = ("election_year", "V_d", "S_d", "V", "S")
FLOAT_COLUMNS = (
    "district_vote_share",
    "district_seat_share",
    "district_valid_votes_per_seat",
    "national_valid_votes_per_seat",
    "district_electoral_weight",
)
ACCOUNTING_ATOL = 1e-9
ACCOUNTING_RTOL = 1e-12
POINT_COLOR = "#176B87"
REFERENCE_COLOR = "#6B7280"
GRID_COLOR = "#D8DEE6"


def parse_exact(value: object) -> Fraction:
    pieces = str(value).strip().split("//", maxsplit=1)
    if len(pieces) != 2:
        raise ValueError(f"Expected exact rational n//d, found {value!r}")
    return Fraction(int(pieces[0]), int(pieces[1]))


def _require_close(
    actual: pd.Series,
    expected: pd.Series | np.ndarray,
    label: str,
    input_path: Path,
) -> None:
    if not np.allclose(
        actual.to_numpy(dtype=float),
        np.asarray(expected, dtype=float),
        rtol=ACCOUNTING_RTOL,
        atol=ACCOUNTING_ATOL,
    ):
        raise ValueError(f"{label} does not reproduce its defining quantities in {input_path}")


def load_district_electoral_weight(input_path: Path) -> pd.DataFrame:
    """Load and validate the exact-audited state-year figure data."""
    if not input_path.is_file():
        raise FileNotFoundError(f"Required diagnostic input not found: {input_path}")

    data = pd.read_csv(input_path)
    missing = sorted(REQUIRED_COLUMNS.difference(data.columns))
    if missing:
        raise ValueError(f"Required columns missing from {input_path}: {', '.join(missing)}")

    for column in INTEGER_COLUMNS:
        numeric = pd.to_numeric(data[column], errors="raise")
        if not np.isfinite(numeric.to_numpy(dtype=float)).all():
            raise ValueError(f"{column} contains non-finite values in {input_path}")
        if not np.equal(numeric, np.floor(numeric)).all():
            raise ValueError(f"{column} contains non-integer values in {input_path}")
        data[column] = numeric.astype(int)

    for column in FLOAT_COLUMNS:
        numeric = pd.to_numeric(data[column], errors="raise")
        if not np.isfinite(numeric.to_numpy(dtype=float)).all():
            raise ValueError(f"{column} contains non-finite values in {input_path}")
        data[column] = numeric.astype(float)

    data["electoral_unit"] = data["electoral_unit"].astype(str).str.strip()
    if (data["electoral_unit"] == "").any():
        raise ValueError(f"Blank electoral-unit label in {input_path}")
    if data.duplicated(["election_year", "electoral_unit"]).any():
        raise ValueError(f"Duplicate state-year row in {input_path}")
    if len(data) != len(EXPECTED_YEARS) * EXPECTED_DISTRICTS:
        raise ValueError(
            f"Expected {len(EXPECTED_YEARS) * EXPECTED_DISTRICTS} state-year rows "
            f"in {input_path}; found {len(data)}"
        )
    if tuple(sorted(data["election_year"].unique())) != EXPECTED_YEARS:
        raise ValueError(
            f"Election years changed in {input_path}: "
            f"{sorted(data['election_year'].unique())}"
        )
    if (data[["V_d", "S_d", "V", "S"]] <= 0).any(axis=None):
        raise ValueError(f"Vote and seat quantities must be positive in {input_path}")

    state_sets: list[set[str]] = []
    for year in EXPECTED_YEARS:
        selected = data.loc[data["election_year"] == year]
        state_sets.append(set(selected["electoral_unit"]))
        if len(selected) != EXPECTED_DISTRICTS:
            raise ValueError(
                f"Expected {EXPECTED_DISTRICTS} districts in {year}; found {len(selected)}"
            )
        if selected["V"].nunique() != 1:
            raise ValueError(f"National vote denominator varies within {year}")
        if int(selected["V"].iloc[0]) != EXPECTED_NATIONAL_VALID_VOTES[year]:
            raise ValueError(
                f"National valid-vote denominator changed in {year}: "
                f"{int(selected['V'].iloc[0]):,}"
            )
        if selected["S"].nunique() != 1 or int(selected["S"].iloc[0]) != EXPECTED_NATIONAL_SEATS:
            raise ValueError(f"National seat total changed in {year}")
        if int(selected["V_d"].sum()) != EXPECTED_NATIONAL_VALID_VOTES[year]:
            raise ValueError(f"District valid votes do not sum to V in {year}")
        if int(selected["S_d"].sum()) != EXPECTED_NATIONAL_SEATS:
            raise ValueError(f"District seats do not sum to 513 in {year}")

    if any(states != state_sets[0] for states in state_sets[1:]):
        raise ValueError(f"Electoral-unit set changes across elections in {input_path}")
    if "SP" not in state_sets[0]:
        raise ValueError(f"São Paulo (SP) is absent from {input_path}")

    expected_weight = (data["S_d"] / data["V_d"]) / (data["S"] / data["V"])
    _require_close(
        data["district_electoral_weight"],
        expected_weight,
        "District electoral weight",
        input_path,
    )
    _require_close(
        data["district_vote_share"],
        data["V_d"] / data["V"],
        "District vote share",
        input_path,
    )
    _require_close(
        data["district_seat_share"],
        data["S_d"] / data["S"],
        "District seat share",
        input_path,
    )
    _require_close(
        data["district_valid_votes_per_seat"],
        data["V_d"] / data["S_d"],
        "District valid votes per seat",
        input_path,
    )
    _require_close(
        data["national_valid_votes_per_seat"],
        data["V"] / data["S"],
        "National valid votes per seat",
        input_path,
    )

    for row in data.itertuples(index=False):
        exact_weight = parse_exact(row.district_electoral_weight_exact)
        expected_exact = Fraction(int(row.S_d), int(row.V_d)) / Fraction(
            int(row.S), int(row.V)
        )
        if exact_weight != expected_exact:
            raise ValueError(
                f"Exact district electoral weight fails for "
                f"{row.election_year}/{row.electoral_unit}"
            )

    return data.sort_values(["election_year", "electoral_unit"]).reset_index(drop=True)


def summarize_district_electoral_weight(data: pd.DataFrame) -> pd.DataFrame:
    """Return one descriptive diagnostic row per election year."""
    varying = (
        data.groupby("electoral_unit", sort=True)["S_d"].nunique().loc[lambda x: x > 1].index
    )
    varying_codes = ",".join(varying)
    rows: list[dict[str, object]] = []

    for year, selected in data.groupby("election_year", sort=True):
        selected = selected.copy()
        minimum = selected.loc[selected["district_electoral_weight"].idxmin()]
        maximum = selected.loc[selected["district_electoral_weight"].idxmax()]
        max_magnitude = int(selected["S_d"].max())
        max_magnitude_states = ",".join(
            sorted(selected.loc[selected["S_d"] == max_magnitude, "electoral_unit"])
        )
        sp = selected.loc[selected["electoral_unit"] == "SP"].iloc[0]
        floor = selected.loc[selected["S_d"] == 8]
        rows.append(
            {
                "election_year": int(year),
                "national_valid_votes": int(selected["V"].iloc[0]),
                "national_seats": int(selected["S"].iloc[0]),
                "district_count": len(selected),
                "mean_district_magnitude": float(selected["S_d"].mean()),
                "median_district_magnitude": float(selected["S_d"].median()),
                "floor_eight_district_count": len(floor),
                "maximum_district_magnitude": max_magnitude,
                "maximum_magnitude_states": max_magnitude_states,
                "states_with_magnitude_changes": len(varying),
                "magnitude_change_state_codes": varying_codes,
                "sp_district_magnitude": int(sp["S_d"]),
                "sp_electoral_weight": float(sp["district_electoral_weight"]),
                "sp_weight_rank_ascending": int(
                    1
                    + (
                        selected["district_electoral_weight"]
                        < float(sp["district_electoral_weight"])
                    ).sum()
                ),
                "minimum_weight_state": str(minimum["electoral_unit"]),
                "minimum_electoral_weight": float(minimum["district_electoral_weight"]),
                "maximum_weight_state": str(maximum["electoral_unit"]),
                "maximum_electoral_weight": float(maximum["district_electoral_weight"]),
                "floor_eight_weight_min": float(floor["district_electoral_weight"].min()),
                "floor_eight_weight_max": float(floor["district_electoral_weight"].max()),
                "floor_eight_weight_mean": float(floor["district_electoral_weight"].mean()),
                "floor_eight_weight_sd": float(
                    floor["district_electoral_weight"].std(ddof=0)
                ),
                "pearson_magnitude_weight": float(
                    selected["S_d"].corr(selected["district_electoral_weight"], method="pearson")
                ),
                "spearman_magnitude_weight": float(
                    selected["S_d"].corr(selected["district_electoral_weight"], method="spearman")
                ),
            }
        )

    return pd.DataFrame(rows)


def _spread_log_positions(
    values: pd.Series,
    *,
    lower: float,
    upper: float,
    minimum_log_gap: float = 0.12,
) -> dict[int, float]:
    """Spread labels vertically on a log axis while preserving their order."""
    ordered = sorted(
        ((int(index), float(value)) for index, value in values.items()),
        key=lambda item: item[1],
    )
    logs = [float(np.log(value)) for _, value in ordered]
    lower_log = float(np.log(lower))
    upper_log = float(np.log(upper))

    for position in range(1, len(logs)):
        logs[position] = max(logs[position], logs[position - 1] + minimum_log_gap)
    if logs and logs[-1] > upper_log:
        shift = logs[-1] - upper_log
        logs = [value - shift for value in logs]
    for position in range(len(logs) - 2, -1, -1):
        logs[position] = min(logs[position], logs[position + 1] - minimum_log_gap)
    if logs and logs[0] < lower_log:
        shift = lower_log - logs[0]
        logs = [value + shift for value in logs]

    return {
        index: float(np.exp(log_value))
        for (index, _), log_value in zip(ordered, logs, strict=True)
    }


def render_district_electoral_weight(data: pd.DataFrame, output_path: Path) -> Path:
    """Render three year panels and save the standalone diagnostic PDF."""
    plt.rcParams.update(
        {
            "font.size": 9,
            "axes.titlesize": 11,
            "axes.labelsize": 10,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    figure, axes = plt.subplots(
        1,
        len(EXPECTED_YEARS),
        figsize=(14.6, 5.5),
        sharex=True,
        sharey=True,
        constrained_layout=False,
    )
    y_limits = (0.5, 7.0)
    y_ticks = (0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0)
    y_tick_labels = ("0.5", "0.75", "1", "1.5", "2", "3", "4", "6")

    for axis, year in zip(axes, EXPECTED_YEARS, strict=True):
        selected = data.loc[data["election_year"] == year].copy()
        axis.scatter(
            selected["S_d"],
            selected["district_electoral_weight"],
            s=31,
            color=POINT_COLOR,
            edgecolor="white",
            linewidth=0.55,
            zorder=3,
        )
        axis.axhline(1.0, color=REFERENCE_COLOR, linewidth=1.0, linestyle=(0, (3, 2)), zorder=1)
        axis.set_yscale("log", base=2)
        axis.set_ylim(*y_limits)
        axis.set_xlim(2.5, 73.5)
        axis.yaxis.set_major_locator(FixedLocator(y_ticks))
        axis.yaxis.set_major_formatter(FixedFormatter(y_tick_labels))
        axis.yaxis.set_minor_locator(NullLocator())
        axis.set_xticks([8, 20, 30, 40, 50, 60, 70])
        axis.grid(axis="y", which="major", color=GRID_COLOR, linewidth=0.65, zorder=0)
        axis.grid(axis="x", which="major", color=GRID_COLOR, linewidth=0.45, alpha=0.55, zorder=0)
        axis.set_title(str(year), pad=8)
        axis.spines["top"].set_visible(False)
        axis.spines["right"].set_visible(False)
        axis.spines["left"].set_color("#89919A")
        axis.spines["bottom"].set_color("#89919A")

        floor = selected.loc[selected["S_d"] == 8]
        label_positions = _spread_log_positions(
            floor["district_electoral_weight"],
            lower=0.58,
            upper=6.55,
        )
        for index, row in floor.iterrows():
            axis.annotate(
                str(row["electoral_unit"]),
                xy=(float(row["S_d"]), float(row["district_electoral_weight"])),
                xytext=(5.7, label_positions[int(index)]),
                textcoords="data",
                ha="right",
                va="center",
                fontsize=7.2,
                color="#27313A",
                arrowprops={
                    "arrowstyle": "-",
                    "color": "#97A2AD",
                    "linewidth": 0.45,
                    "shrinkA": 1,
                    "shrinkB": 2,
                },
                bbox={
                    "boxstyle": "round,pad=0.08",
                    "facecolor": "white",
                    "edgecolor": "none",
                    "alpha": 0.82,
                },
                zorder=4,
            )

        directly_labeled = set(floor.index)
        low_magnitude = selected.loc[(selected["S_d"] > 8) & (selected["S_d"] <= 10)]
        extremes = pd.concat(
            [
                selected.nsmallest(2, "district_electoral_weight"),
                selected.nlargest(2, "district_electoral_weight"),
            ]
        ).drop_duplicates()
        remaining = pd.concat([low_magnitude, extremes]).drop_duplicates()
        remaining = remaining.loc[~remaining.index.isin(directly_labeled)]

        for index, row in remaining.iterrows():
            x_value = float(row["S_d"])
            y_value = float(row["district_electoral_weight"])
            if x_value >= 60:
                offset = (-6, 6)
                alignment = "right"
            elif int(index) % 2:
                offset = (5, -9)
                alignment = "left"
            else:
                offset = (5, 6)
                alignment = "left"
            axis.annotate(
                str(row["electoral_unit"]),
                xy=(x_value, y_value),
                xytext=offset,
                textcoords="offset points",
                ha=alignment,
                va="center",
                fontsize=7.5,
                fontweight="semibold" if str(row["electoral_unit"]) == "SP" else "normal",
                color="#27313A",
                bbox={
                    "boxstyle": "round,pad=0.08",
                    "facecolor": "white",
                    "edgecolor": "none",
                    "alpha": 0.78,
                },
                zorder=4,
            )

    figure.suptitle(
        "District electoral weight by district magnitude",
        x=0.51,
        y=0.98,
        fontsize=14,
        fontweight="semibold",
    )
    figure.text(
        0.51,
        0.932,
        "Each point is a state; 1 is the national seats-per-valid-vote rate.",
        ha="center",
        va="top",
        fontsize=9.5,
        color="#4B5563",
    )
    figure.supxlabel(r"District magnitude ($S_d$)", x=0.51, y=0.075, fontsize=10)
    figure.supylabel(
        r"District electoral weight $(S_d/V_d)/(513/V)$",
        x=0.035,
        y=0.52,
        fontsize=10,
    )
    figure.text(
        0.51,
        0.018,
        "Labels identify all 8–10-seat districts and the two lowest and highest "
        "weights in each election; "
        "the vertical scale is logarithmic.",
        ha="center",
        va="bottom",
        fontsize=8,
        color="#5F6872",
    )
    figure.subplots_adjust(left=0.085, right=0.985, bottom=0.16, top=0.865, wspace=0.12)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(
        output_path,
        bbox_inches="tight",
        metadata={
            "Title": "District electoral weight by district magnitude",
            "Author": "Reproducible electoral-inversions diagnostic",
        },
    )
    plt.close(figure)
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"Audited state-year CSV (default: {DEFAULT_INPUT})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Diagnostic PDF (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--summary-output",
        type=Path,
        default=DEFAULT_SUMMARY_OUTPUT,
        help=f"Derived diagnostic summary CSV (default: {DEFAULT_SUMMARY_OUTPUT})",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    data = load_district_electoral_weight(args.input)
    summary = summarize_district_electoral_weight(data)

    args.summary_output.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(args.summary_output, index=False, float_format="%.12g")
    output = render_district_electoral_weight(data, args.output)

    changing = int(summary["states_with_magnitude_changes"].iloc[0])
    print(f"Validated {len(data)} state-year rows from {args.input}")
    print(f"Saved diagnostic plot to {output}")
    print(f"Saved diagnostic summary to {args.summary_output}")
    print(
        "District magnitudes are constant across elections."
        if changing == 0
        else f"District magnitudes change for {changing} state(s)."
    )
    print(
        summary[
            [
                "election_year",
                "mean_district_magnitude",
                "median_district_magnitude",
                "floor_eight_district_count",
                "maximum_district_magnitude",
                "sp_electoral_weight",
                "minimum_weight_state",
                "maximum_weight_state",
                "spearman_magnitude_weight",
            ]
        ].to_string(index=False)
    )


if __name__ == "__main__":
    main()
