module ManuscriptValues

# Manuscript numerical values: the sole prose selection and formatting contract.
# Analysis is already complete. SOURCE_FILES in the support file points only to
# production CSVs, never generated TeX, plots, or historical expected values.
include("ManuscriptValueSupport.jl")
export MANUSCRIPT_VALUE_SPECS, load_manuscript_sources, build_registry,
       write_manuscript_values, validate_registry, validate_manuscript

# Each group below explicitly names the claim, authoritative object, selector,
# election/universe/k and complete fixed membership where applicable. Field entries
# are (semantic suffix, source metric, display rule[, aggregation]). Macro and key
# are prefix + suffix. No ordinal position selects a substantive case.
# Strongest = minimum national vote share, then party count, canonical coalition_id.
# Linked span/omission selectors follow that same k=1 winner, not today's label.
# pct2/pct1 multiply a raw share by 100; decimal2/3 do not. Words preserve prose.
# Table rounding remains in the table builders and may preserve component closure.
const MANUSCRIPT_VALUE_SPECS = [

    value_group("IdeologySeatWinningTwentyFourteenKZeroStrongest",
        "2014 seat_winning k=0 strongest minimal inversion",
        :ideology, (; election = 2014, ideological_universe = "seat_winning", k = 0, minimal_inversion = true), [
            ("VotePct", :vote_share, :pct2),
            ("Quota", :q_C, :decimal2),
            ("Differential", :d_C, :decimal2),
            ("PartiesWords", :party_count, :words),
            ("Label", :label, :text),
            ("Seats", :seats, :integer),
            ("Ratio", :R_C, :decimal3),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :strongest),
    value_group("IdeologySeatWinningTwentyEighteenKZeroPTPSDB",
        "2018 seat_winning k=0 PTPSDB substantive interval",
        :ideology, (; election = 2018, ideological_universe = "seat_winning", k = 0, left_endpoint = "PT", right_endpoint = "PSDB", minimal_inversion = true), [
            ("VotePct", :vote_share, :pct2),
            ("Quota", :q_C, :decimal2),
            ("Differential", :d_C, :decimal2),
            ("Within", :A_C, :decimal2),
            ("Between", :B_C, :decimal2),
            ("Ratio", :R_C, :decimal3),
            ("Seats", :seats, :integer),
            ("PartiesWords", :party_count, :words),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :unique,
        members = ["PT", "PDT", "PSB", "REDE", "PPS", "PV", "PTB", "AVANTE", "SOLIDARIEDADE", "PMN", "PHS", "MDB", "PSD", "PSDB"]),
    value_group("IdeologySeatWinningTwentyTwentyTwoKZeroMDBUniao",
        "2022 seat_winning k=0 MDBUniao substantive interval",
        :ideology, (; election = 2022, ideological_universe = "seat_winning", k = 0, left_endpoint = "MDB", right_endpoint = "UNIÃO", minimal_inversion = true), [
            ("VotePct", :vote_share, :pct2),
            ("Quota", :q_C, :decimal2),
            ("Required", :r_C, :decimal2),
            ("Differential", :d_C, :decimal2),
            ("Within", :A_C, :decimal2),
            ("Between", :B_C, :decimal2),
            ("Ratio", :R_C, :decimal3),
            ("Seats", :seats, :integer),
            ("PartiesWords", :party_count, :words),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :unique,
        members = ["MDB", "PSDB", "PSD", "PODE", "PROS", "PTB", "PP", "REPUBLICANOS", "PSC", "UNIÃO"]),
    value_group("IdeologySeatWinningTwentyTwentyTwoKZeroPPPL",
        "2022 seat_winning k=0 PPPL substantive interval",
        :ideology, (; election = 2022, ideological_universe = "seat_winning", k = 0, left_endpoint = "PP", right_endpoint = "PL", minimal_inversion = true), [
            ("VotePct", :vote_share, :pct2),
            ("Quota", :q_C, :decimal2),
            ("Required", :r_C, :decimal2),
            ("Differential", :d_C, :decimal2),
            ("Within", :A_C, :decimal2),
            ("Between", :B_C, :decimal2),
            ("Ratio", :R_C, :decimal3),
            ("Seats", :seats, :integer),
            ("PartiesWords", :party_count, :words),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :unique,
        members = ["PP", "REPUBLICANOS", "PSC", "UNIÃO", "PATRIOTA", "NOVO", "PL"]),
    value_group("IdeologySeatWinningTwentyFourteenKOneStrongest",
        "2014 seat_winning k=1 strongest minimal inversion",
        :ideology, (; election = 2014, ideological_universe = "seat_winning", k = 1, minimal_inversion = true), [
            ("PartiesWords", :party_count, :words),
            ("Label", :label, :text),
            ("VotePct", :vote_share, :pct2),
            ("Seats", :seats, :integer),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :strongest),
    value_group("IdeologySeatWinningTwentyTwentyTwoKOneStrongest",
        "2022 seat_winning k=1 strongest minimal inversion",
        :ideology, (; election = 2022, ideological_universe = "seat_winning", k = 1, minimal_inversion = true), [
            ("PartiesWords", :party_count, :words),
            ("Label", :label, :text),
            ("VotePct", :vote_share, :pct2),
            ("Seats", :seats, :integer),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :strongest),
    value_group("IdeologySeatWinningTwentyEighteenKOneStrongest",
        "2018 seat_winning k=1 strongest minimal inversion",
        :ideology, (; election = 2018, ideological_universe = "seat_winning", k = 1, minimal_inversion = true), [
            ("Label", :label_with_gap, :text),
            ("PartiesWords", :party_count, :words),
            ("Seats", :seats, :integer),
            ("VotePct", :vote_share, :pct2),
            ("Differential", :d_C, :decimal2),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :strongest),
    value_group("IdeologyAllPartiesTwentyTwentyTwoKZeroMDBUniao",
        "2022 all_parties k=0 MDBUniao substantive interval",
        :ideology, (; election = 2022, ideological_universe = "all_parties", k = 0, left_endpoint = "MDB", right_endpoint = "UNIÃO", minimal_inversion = true), [
            ("Within", :A_C, :decimal2),
            ("Between", :B_C, :decimal2),
        ]; domain = "ideological", universe = "all_parties",
        k = 0, selector = :unique,
        members = ["MDB", "PMN", "PSDB", "PSD", "PMB", "PODE", "PROS", "PRTB", "AGIR", "PTB", "PP", "DC", "REPUBLICANOS", "PSC", "UNIÃO"]),
    value_group("PartyTwentyFourteenPMDB",
        "2014 PMDB party accounting",
        :party, (; election_year = 2014, party = "PMDB"), [
            ("DifferentialMagnitude", :d_i, :abs2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyFourteenPSD",
        "2014 PSD party accounting",
        :party, (; election_year = 2014, party = "PSD"), [
            ("DifferentialMagnitude", :d_i, :abs2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyFourteenPTB",
        "2014 PTB party accounting",
        :party, (; election_year = 2014, party = "PTB"), [
            ("DifferentialMagnitude", :d_i, :abs2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyFourteenPSDB",
        "2014 PSDB party accounting",
        :party, (; election_year = 2014, party = "PSDB"), [
            ("DifferentialMagnitude", :d_i, :abs2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyFourteenPSOL",
        "2014 PSOL party accounting",
        :party, (; election_year = 2014, party = "PSOL"), [
            ("DifferentialMagnitude", :d_i, :abs2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyEighteenPP",
        "2018 PP party accounting",
        :party, (; election_year = 2018, party = "PP"), [
            ("DifferentialMagnitude", :d_i, :abs2),
            ("Within", :A_i, :decimal2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyEighteenPR",
        "2018 PR party accounting",
        :party, (; election_year = 2018, party = "PR"), [
            ("DifferentialMagnitude", :d_i, :abs2),
            ("Within", :A_i, :decimal2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyEighteenMDB",
        "2018 MDB party accounting",
        :party, (; election_year = 2018, party = "MDB"), [
            ("DifferentialMagnitude", :d_i, :abs2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyEighteenPSL",
        "2018 PSL party accounting",
        :party, (; election_year = 2018, party = "PSL"), [
            ("DifferentialMagnitude", :d_i, :abs2),
            ("Between", :B_i, :decimal2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyEighteenNOVO",
        "2018 NOVO party accounting",
        :party, (; election_year = 2018, party = "NOVO"), [
            ("DifferentialMagnitude", :d_i, :abs2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyTwentyTwoPL",
        "2022 PL party accounting",
        :party, (; election_year = 2022, party = "PL"), [
            ("DifferentialMagnitude", :d_i, :abs2),
            ("Ratio", :R_i, :decimal3),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyTwentyTwoUniao",
        "2022 UNIÃO party accounting",
        :party, (; election_year = 2022, party = "UNIÃO"), [
            ("DifferentialMagnitude", :d_i, :abs2),
            ("Within", :A_i, :decimal2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyTwentyTwoPT",
        "2022 PT party accounting",
        :party, (; election_year = 2022, party = "PT"), [
            ("DifferentialMagnitude", :d_i, :abs2),
            ("Within", :A_i, :decimal2),
            ("Between", :B_i, :decimal2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyTwentyTwoPP",
        "2022 PP party accounting",
        :party, (; election_year = 2022, party = "PP"), [
            ("DifferentialMagnitude", :d_i, :abs2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyTwentyTwoPV",
        "2022 PV party accounting",
        :party, (; election_year = 2022, party = "PV"), [
            ("DifferentialMagnitude", :d_i, :abs2),
            ("Ratio", :R_i, :decimal3),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("IdeologySeatWinningTwentyTwentyTwoKZeroPTPP",
        "2022 seat_winning k=0 PTPP substantive interval",
        :ideology, (; election = 2022, ideological_universe = "seat_winning", k = 0, left_endpoint = "PT", right_endpoint = "PP", minimal_seat_majority = true, inversion = false), [
            ("DifferentialMagnitude", :d_C, :abs2),
            ("PartiesWords", :party_count, :words),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :unique,
        members = ["PT", "PSB", "REDE", "PDT", "PV", "SOLIDARIEDADE", "CIDADANIA", "AVANTE", "MDB", "PSDB", "PSD", "PODE", "PROS", "PTB", "PP"]),
    value_group("IdeologySeatWinningTwentyTwentyTwoKZeroPSBPSC",
        "2022 seat_winning k=0 PSBPSC substantive interval",
        :ideology, (; election = 2022, ideological_universe = "seat_winning", k = 0, left_endpoint = "PSB", right_endpoint = "PSC", minimal_seat_majority = true, inversion = false), [
            ("DifferentialMagnitude", :d_C, :abs2),
            ("PartiesWords", :party_count, :words),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :unique,
        members = ["PSB", "REDE", "PDT", "PV", "SOLIDARIEDADE", "CIDADANIA", "AVANTE", "MDB", "PSDB", "PSD", "PODE", "PROS", "PTB", "PP", "REPUBLICANOS", "PSC"]),
    value_group("CabinetTwentyFourteenDilma",
        "Dilma inverted cabinet cabinet/2014/2016.2",
        :cabinet, (; case_id = "cabinet/2014/2016.2"), [
            ("VotePct", :vote_share, :pct2),
            ("Quota", :q_C, :decimal2),
            ("Required", :r_C, :decimal2),
            ("Differential", :d_C, :decimal2),
            ("Ratio", :R_C, :decimal3),
            ("Within", :A_C, :decimal2),
            ("Between", :B_C, :decimal2),
            ("WithinAdjustedQuota", :within_adjusted_quota, :decimal2),
            ("Seats", :s_C, :integer),
            ("DaysWords", :period_days, :words),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("CabinetTwentyFourteenTemer",
        "Temer inverted cabinet cabinet/2014/2017.1",
        :cabinet, (; case_id = "cabinet/2014/2017.1"), [
            ("VotePct", :vote_share, :pct2),
            ("Quota", :q_C, :decimal2),
            ("Required", :r_C, :decimal2),
            ("Differential", :d_C, :decimal2),
            ("Ratio", :R_C, :decimal3),
            ("Seats", :s_C, :integer),
            ("Days", :period_days, :integer),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("CabinetTwentyEighteenBolsonaro",
        "Bolsonaro inverted cabinet cabinet/2018/2021.3/2022.1",
        :cabinet, (; case_id = "cabinet/2018/2021.3/2022.1"), [
            ("VotePct", :vote_share, :pct2),
            ("Quota", :q_C, :decimal2),
            ("Differential", :d_C, :decimal2),
            ("Ratio", :R_C, :decimal3),
            ("Within", :A_C, :decimal2),
            ("Between", :B_C, :decimal2),
            ("Days", :period_days, :integer),
            ("Seats", :s_C, :integer),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("CabinetTwentyTwentyTwoLula",
        "Lula inverted cabinet cabinet/2022/2023.1",
        :cabinet, (; case_id = "cabinet/2022/2023.1"), [
            ("VotePct", :vote_share, :pct2),
            ("Quota", :q_C, :decimal2),
            ("Differential", :d_C, :decimal2),
            ("Ratio", :R_C, :decimal3),
            ("Required", :r_C, :decimal2),
            ("Seats", :s_C, :integer),
            ("Days", :period_days, :integer),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("CabinetTwentyEighteenBolsonaroAfterPSC",
        "BolsonaroAfterPSC transition period",
        :periods, (; election_year = 2018, cabinet_period = "2022.2"), [
            ("Differential", :d_C, :decimal2),
            ("Seats", :s_C, :integer),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("CabinetTwentyTwentyTwoLulaExpanded",
        "LulaExpanded transition period",
        :periods, (; election_year = 2022, cabinet_period = "2023.2"), [
            ("VotePct", :vote_share, :pct2),
            ("Seats", :s_C, :integer),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("IdeologySeatWinningTwentyFourteenKZeroSummary",
        "2014 seat_winning k=0 domain summary",
        :summary, (; election = 2014, ideological_universe = "seat_winning", k = 0), [
            ("MinimalInversionsWords", :minimal_inversions, :words),
            ("MinimalSeatMajorityCoalitionsWords", :minimal_seat_majority_coalitions, :words),
            ("IdeologicalPartyCount", :ideological_party_count, :integer),
            ("InvertedMembersMinWords", :inverted_members_min, :words),
            ("InvertedMembersMaxWords", :inverted_members_max, :words),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :unique),
    value_group("IdeologySeatWinningTwentyEighteenKZeroSummary",
        "2018 seat_winning k=0 domain summary",
        :summary, (; election = 2018, ideological_universe = "seat_winning", k = 0), [
            ("MinimalInversionsWords", :minimal_inversions, :words),
            ("MinimalSeatMajorityCoalitionsWords", :minimal_seat_majority_coalitions, :words),
            ("IdeologicalPartyCount", :ideological_party_count, :integer),
            ("NonInvertedMinimalMajoritiesWords", :non_inverted_minimal_majorities, :words),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :unique),
    value_group("IdeologySeatWinningTwentyTwentyTwoKZeroSummary",
        "2022 seat_winning k=0 domain summary",
        :summary, (; election = 2022, ideological_universe = "seat_winning", k = 0), [
            ("MinimalInversionsWords", :minimal_inversions, :words),
            ("MinimalSeatMajorityCoalitionsWords", :minimal_seat_majority_coalitions, :words),
            ("IdeologicalPartyCount", :ideological_party_count, :integer),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :unique),
    value_group("IdeologyAllPartiesTwentyFourteenKZeroSummary",
        "2014 all_parties k=0 domain summary",
        :summary, (; election = 2014, ideological_universe = "all_parties", k = 0), [
            ("IdeologicalPartyCount", :ideological_party_count, :integer),
        ]; domain = "ideological", universe = "all_parties",
        k = 0, selector = :unique),
    value_group("IdeologyAllPartiesTwentyEighteenKZeroSummary",
        "2018 all_parties k=0 domain summary",
        :summary, (; election = 2018, ideological_universe = "all_parties", k = 0), [
            ("IdeologicalPartyCount", :ideological_party_count, :integer),
        ]; domain = "ideological", universe = "all_parties",
        k = 0, selector = :unique),
    value_group("IdeologyAllPartiesTwentyTwentyTwoKZeroSummary",
        "2022 all_parties k=0 domain summary",
        :summary, (; election = 2022, ideological_universe = "all_parties", k = 0), [
            ("IdeologicalPartyCount", :ideological_party_count, :integer),
        ]; domain = "ideological", universe = "all_parties",
        k = 0, selector = :unique),
    value_group("IdeologySeatWinningTwentyFourteenKOneSummary",
        "2014 seat_winning k=1 domain summary",
        :summary, (; election = 2014, ideological_universe = "seat_winning", k = 1), [
            ("MinimalInversions", :minimal_inversions, :integer),
            ("MinimalSeatMajorityCoalitions", :minimal_seat_majority_coalitions, :integer),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :unique),
    value_group("IdeologySeatWinningTwentyEighteenKOneSummary",
        "2018 seat_winning k=1 domain summary",
        :summary, (; election = 2018, ideological_universe = "seat_winning", k = 1), [
            ("MinimalInversions", :minimal_inversions, :integer),
            ("MinimalSeatMajorityCoalitions", :minimal_seat_majority_coalitions, :integer),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :unique),
    value_group("IdeologySeatWinningTwentyTwentyTwoKOneSummary",
        "2022 seat_winning k=1 domain summary",
        :summary, (; election = 2022, ideological_universe = "seat_winning", k = 1), [
            ("MinimalInversions", :minimal_inversions, :integer),
            ("MinimalSeatMajorityCoalitions", :minimal_seat_majority_coalitions, :integer),
            ("MinimalInversionsWords", :minimal_inversions, :words),
            ("InvertedMembersMinWords", :inverted_members_min, :words),
            ("InvertedMembersMaxWords", :inverted_members_max, :words),
            ("InvertedMembersMedianWords", :inverted_members_median, :words),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :unique),
    value_group("IdeologySeatWinningKZeroTotals",
        "seat_winning k=0 totals across elections",
        :summary, (; ideological_universe = "seat_winning", k = 0), [
            ("InversionsWords", :minimal_inversions, :words, :sum),
            ("MajoritiesWords", :minimal_seat_majority_coalitions, :words, :sum),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :aggregate),
    value_group("IdeologyAllPartiesKZeroTotals",
        "all_parties k=0 totals across elections",
        :summary, (; ideological_universe = "all_parties", k = 0), [
            ("InversionsWords", :minimal_inversions, :words, :sum),
        ]; domain = "ideological", universe = "all_parties",
        k = 0, selector = :aggregate),
    value_group("IdeologyAllPartiesTwentyFourteenKOneSummary",
        "2014 all_parties k=1 domain summary",
        :summary, (; election = 2014, ideological_universe = "all_parties", k = 1), [
            ("MinimalInversions", :minimal_inversions, :integer),
        ]; domain = "ideological", universe = "all_parties",
        k = 1, selector = :unique),
    value_group("IdeologyAllPartiesTwentyEighteenKOneSummary",
        "2018 all_parties k=1 domain summary",
        :summary, (; election = 2018, ideological_universe = "all_parties", k = 1), [
            ("MinimalInversions", :minimal_inversions, :integer),
        ]; domain = "ideological", universe = "all_parties",
        k = 1, selector = :unique),
    value_group("IdeologyAllPartiesTwentyTwentyTwoKOneSummary",
        "2022 all_parties k=1 domain summary",
        :summary, (; election = 2022, ideological_universe = "all_parties", k = 1), [
            ("MinimalInversions", :minimal_inversions, :integer),
        ]; domain = "ideological", universe = "all_parties",
        k = 1, selector = :unique),
    value_group("IdeologySeatWinningKOneSurvivingConnected",
        "Connected minimal majorities still minimal under k=1",
        :ideology, (; ideological_universe = "seat_winning", k = 1, gap_count = 0, minimal_seat_majority = true), [
            ("CountWords", :count, :words, :sum),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :aggregate),
    value_group("IdeologySeatWinningKZeroAllInversions",
        "All connected inversions, including nonminimal cases",
        :ideology, (; ideological_universe = "seat_winning", k = 0, inversion = true), [
            ("CountWords", :count, :words, :sum),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :aggregate),
    value_group("IdeologySeatWinningKOneNegativeWithin",
        "Minimal one-gap inversions with negative within-district component",
        :ideology, (; ideological_universe = "seat_winning", k = 1, minimal_inversion = true), [
            ("CountWords", :A_C, :words, :count_negative),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :aggregate),
    value_group("IdeologySeatWinningTwentyFourteenKOneNegativeWithin",
        "Minimal one-gap inversions with negative within-district component",
        :ideology, (; ideological_universe = "seat_winning", k = 1, minimal_inversion = true, election = 2014), [
            ("CountWords", :A_C, :words, :count_negative),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :aggregate),
    value_group("IdeologySeatWinningTwentyTwentyTwoKOneNegativeWithin",
        "Minimal one-gap inversions with negative within-district component",
        :ideology, (; ideological_universe = "seat_winning", k = 1, minimal_inversion = true, election = 2022), [
            ("CountWords", :A_C, :words, :count_negative),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :aggregate),
    value_group("IdeologyAllPartiesKZeroPositiveWithin",
        "All-party connected minimal inversions with positive within component",
        :ideology, (; ideological_universe = "all_parties", k = 0, minimal_inversion = true), [
            ("CountWords", :A_C, :words, :count_positive),
        ]; domain = "ideological", universe = "all_parties",
        k = 0, selector = :aggregate),
    value_group("IdeologySeatWinningTwentyFourteenKOnePT",
        "PT membership among 2014 primary one-gap minimal inversions",
        :ideology, (; election = 2014, ideological_universe = "seat_winning", k = 1, minimal_inversion = true), [
            ("CountWords", :includes_PT, :words, :sum),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :aggregate),
    value_group("IdeologySeatWinningTwentyTwentyTwoKOneMDBUniao",
        "Gapped minimal inversions spanning MDB--UNIÃO",
        :ideology, (; election = 2022, ideological_universe = "seat_winning", k = 1, minimal_inversion = true, left_endpoint = "MDB", right_endpoint = "UNIÃO", gap_count = 1), [
            ("CountWords", :count, :Words, :sum),
        ]; domain = "ideological", universe = "seat_winning",
        k = 1, selector = :aggregate),
    value_group("CabinetPeriods",
        "All observed cabinet periods",
        :periods, NamedTuple(), [
            ("CountWords", :count, :words, :sum),
            ("Count", :count, :integer, :sum),
            ("OverrepresentedCount", :d_C, :integer, :count_positive),
            ("OverrepresentedCountWords", :d_C, :words, :count_positive),
            ("UnderrepresentedCountWords", :d_C, :words, :count_negative),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :aggregate),
    value_group("CabinetInversions",
        "Observed inverted cabinet periods and distinct accounting vectors",
        :cabinet, (; case_domain = "cabinet"), [
            ("CountWords", :count, :words, :sum),
            ("UniqueVectorsWords", :numerical_vector_group, :words, :unique_count),
            ("CountCapitalized", :count, :Words, :sum),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :aggregate),
    value_group("CabinetComponents",
        "District component signs across all cabinet periods",
        :linkage, NamedTuple(), [
            ("PositiveBetweenWords", :B_C, :words, :count_positive),
            ("PositiveWithinWords", :A_C, :words, :count_positive),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :aggregate),
    value_group("CabinetTwentyFourteenDuration",
        "2014 mandate coverage and inversion duration",
        :duration, (; election_year = 2014), [
            ("InversionDays", :inversion_days, :integer),
            ("CoveredDays", :covered_days, :integer),
            ("InversionsWords", :n_inversion_periods, :words),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("CabinetTwentyEighteenDuration",
        "2018 mandate coverage and inversion duration",
        :duration, (; election_year = 2018), [
            ("InversionDays", :inversion_days, :integer),
            ("CoveredDays", :covered_days, :integer),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("CabinetTwentyTwentyTwoDuration",
        "2022 mandate coverage and inversion duration",
        :duration, (; election_year = 2022), [
            ("InversionDays", :inversion_days, :integer),
            ("CoveredDays", :covered_days, :integer),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyFourteenEverCabinet",
        "2014 mean vote share by cabinet participation",
        :size, (; election = "2014", ever_in_cabinet = true), [
            ("MeanVotePct", :mean_vote_share, :pct2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyFourteenNeverCabinet",
        "2014 mean vote share by cabinet participation",
        :size, (; election = "2014", ever_in_cabinet = false), [
            ("MeanVotePct", :mean_vote_share, :pct2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyFourteenLarge",
        "2014 parties at the descriptive 5 percent benchmark",
        :size_groups, (; election = "2014", size_group = ">=5%"), [
            ("PositiveWithinWords", :positive_A_i_count, :words),
            ("CountWords", :n, :words),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyEighteenEverCabinet",
        "2018 mean vote share by cabinet participation",
        :size, (; election = "2018", ever_in_cabinet = true), [
            ("MeanVotePct", :mean_vote_share, :pct2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyEighteenNeverCabinet",
        "2018 mean vote share by cabinet participation",
        :size, (; election = "2018", ever_in_cabinet = false), [
            ("MeanVotePct", :mean_vote_share, :pct2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyEighteenLarge",
        "2018 parties at the descriptive 5 percent benchmark",
        :size_groups, (; election = "2018", size_group = ">=5%"), [
            ("PositiveWithinWords", :positive_A_i_count, :words),
            ("CountWords", :n, :words),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyTwentyTwoEverCabinet",
        "2022 mean vote share by cabinet participation",
        :size, (; election = "2022", ever_in_cabinet = true), [
            ("MeanVotePct", :mean_vote_share, :pct2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyTwentyTwoNeverCabinet",
        "2022 mean vote share by cabinet participation",
        :size, (; election = "2022", ever_in_cabinet = false), [
            ("MeanVotePct", :mean_vote_share, :pct2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("PartyTwentyTwentyTwoLarge",
        "2022 parties at the descriptive 5 percent benchmark",
        :size_groups, (; election = "2022", size_group = ">=5%"), [
            ("PositiveWithinWords", :positive_A_i_count, :words),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :unique),
    value_group("IdeologyAllPartiesTwentyEighteenKOneStrongest",
        "2018 all_parties k=1 strongest minimal inversion",
        :ideology, (; election = 2018, ideological_universe = "all_parties", k = 1, minimal_inversion = true), [
            ("VotePct", :vote_share, :pct2),
            ("Label", :label_with_gap, :text),
            ("Seats", :seats, :integer),
        ]; domain = "ideological", universe = "all_parties",
        k = 1, selector = :strongest),
    value_group("CabinetTwentyFourteenDilmaBridge",
        "2016.2 cabinet parliamentary closure and closest intervals",
        :bridge, (; election_year = 2014, ideological_universe = "seat_winning", cabinet_period = "2016.2"), [
            ("ClosureParties", :closure_n_parties, :integer),
            ("ClosureVotePct", :closure_vote_share_pct, :decimal2),
            ("ClosureSeats", :closure_seats, :integer),
            ("GapWords", :closure_gap_n, :words),
        ]; domain = "cabinet_bridge", universe = "seat_winning",
        k = missing, selector = :unique),
    value_group("CabinetTwentyFourteenTemerBridge",
        "2017.1 cabinet parliamentary closure and closest intervals",
        :bridge, (; election_year = 2014, ideological_universe = "seat_winning", cabinet_period = "2017.1"), [
            ("ClosureParties", :closure_n_parties, :integer),
            ("GapWords", :closure_gap_n, :words),
            ("ClosureVotePct", :closure_vote_share_pct, :decimal2),
            ("ClosureSeats", :closure_seats, :integer),
            ("ClosestWinningVotePct", :closest_mcw_vote_share_pct, :decimal2),
            ("ClosestWinningSeats", :closest_mcw_seats, :integer),
        ]; domain = "cabinet_bridge", universe = "seat_winning",
        k = missing, selector = :unique),
    value_group("CabinetTwentyEighteenBolsonaroBridge",
        "2021.3/2022.1 cabinet parliamentary closure and closest intervals",
        :bridge, (; election_year = 2018, ideological_universe = "seat_winning", cabinet_period = "2021.3/2022.1"), [
            ("ClosurePartiesWords", :closure_n_parties, :words),
            ("GapWords", :closure_gap_n, :words),
            ("ClosureVotePct", :closure_vote_share_pct, :decimal2),
            ("ClosureSeats", :closure_seats, :integer),
            ("ClosestWinningVotePct", :closest_mcw_vote_share_pct, :decimal2),
            ("ClosestInversionJaccard", :closest_mci_jaccard, :decimal3),
            ("ClosestInversionSeats", :closest_mci_seats, :integer),
            ("ClosestWinningSeats", :closest_mcw_seats, :integer),
        ]; domain = "cabinet_bridge", universe = "seat_winning",
        k = missing, selector = :unique),
    value_group("CabinetTwentyTwentyTwoLulaBridge",
        "2023.1 cabinet parliamentary closure and closest intervals",
        :bridge, (; election_year = 2022, ideological_universe = "seat_winning", cabinet_period = "2023.1"), [
            ("ClosureParties", :closure_n_parties, :integer),
            ("GapWords", :closure_gap_n, :words),
            ("ClosureVotePct", :closure_vote_share_pct, :decimal2),
            ("ClosureSeats", :closure_seats, :integer),
            ("ClosestWinningVotePct", :closest_mcw_vote_share_pct, :decimal2),
            ("ClosestWinningSeats", :closest_mcw_seats, :integer),
        ]; domain = "cabinet_bridge", universe = "seat_winning",
        k = missing, selector = :unique),
    value_group("CabinetTwentyFourteenTemerTransitionBridge",
        "2016.4 cabinet parliamentary closure and closest intervals",
        :bridge, (; election_year = 2014, ideological_universe = "seat_winning", cabinet_period = "2016.4"), [
            ("UnweightedChange", :delta_cabinet_mean_ideology_value_unweighted, :decimal2),
            ("SeatWeightedChange", :delta_cabinet_mean_ideology_value_seat_weighted, :decimal2),
        ]; domain = "cabinet_bridge", universe = "seat_winning",
        k = missing, selector = :unique),
    value_group("CabinetBridge",
        "Range of gaps in observed parliamentary cabinet closures",
        :bridge, (; ideological_universe = "seat_winning"), [
            ("MinimumGapsWords", :closure_gap_n, :words, :min),
            ("MaximumGapsWords", :closure_gap_n, :words, :max),
        ]; domain = "cabinet_bridge", universe = "seat_winning",
        k = missing, selector = :aggregate),
    value_group("DistrictMagnitude",
        "District magnitude distribution (2014 apportionment, unchanged across analyzed elections)",
        :district, (; election_year = 2014), [
            ("MedianWords", :S_d, :words, :median),
            ("MeanWords", :S_d, :words, :mean),
        ]; domain = "district", universe = "not_applicable",
        k = missing, selector = :aggregate),
    value_group("DistrictEightSeat",
        "Districts at the statutory eight-seat floor (2014 apportionment)",
        :district, (; election_year = 2014, S_d = 8), [
            ("CountCapitalized", :count, :Words, :sum),
            ("CountWords", :count, :words, :sum),
        ]; domain = "district", universe = "not_applicable",
        k = missing, selector = :aggregate),
    value_group("IdeologySeatWinningTwentyEighteenStrongestFullSpan",
        "Full k=0 span of the strongest 2018 seat-winning k=1 minimal inversion",
        :ideology, (; election = 2018, ideological_universe = "seat_winning", k = 0), [
            ("PartiesWords", :party_count, :words),
            ("Seats", :seats, :integer),
            ("VotePct", :vote_share, :pct2),
            ("Differential", :d_C, :decimal2),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :strongest_span),
    value_group("PartyTwentyEighteenStrongestOmission",
        "Omitted party in the strongest 2018 seat-winning k=1 minimal inversion",
        :party, (; election_year = 2018), [
            ("Label", :party, :text),
            ("SeatsWords", :s_i, :words),
            ("DifferentialMagnitude", :d_i, :abs2),
        ]; domain = "party", universe = "not_applicable",
        k = missing, selector = :strongest_omission),
    value_group("IdeologySeatWinningTwentyFourteenKZeroOther",
        "2014 connected inversions excluding the strongest",
        :ideology, (; election = 2014, ideological_universe = "seat_winning", k = 0, minimal_inversion = true), [
            ("CountWords", :count, :words, :sum_minus_one),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :aggregate),
    value_group("IdeologySeatWinningTwentyFourteenKZeroNegativeBetween",
        "2014 minimal connected inversions with negative between-district component",
        :ideology, (; election = 2014, ideological_universe = "seat_winning", k = 0, minimal_inversion = true), [
            ("CountWords", :B_C, :words, :count_negative),
        ]; domain = "ideological", universe = "seat_winning",
        k = 0, selector = :aggregate),
    value_group("CabinetDistrictConcentration",
        "Range of within-district concentration across inverted cabinet vectors",
        :cabinet_district, NamedTuple(), [
            ("MinimumPositiveWords", :positive_count, :words, :min),
            ("MaximumPositiveWords", :positive_count, :words, :max),
            ("MinimumTopThreePct", :top_three_positive_share, :pct1, :min),
            ("MaximumTopThreePct", :top_three_positive_share, :pct1, :max),
            ("MinimumNinetyWords", :districts_for_ninety_pct, :words, :min),
            ("MaximumNinetyWords", :districts_for_ninety_pct, :words, :max),
        ]; domain = "cabinet", universe = "not_applicable",
        k = missing, selector = :aggregate),
    value_group("PartyTwentyFourteenFragmentation",
        "2014 effective party numbers: inverse sum of squared production vote/seat shares",
        :fragmentation, (; election_year = 2014), [
            ("Electoral", :effective_electoral, :decimal2),
            ("Parliamentary", :effective_parliamentary, :decimal2),
        ]; domain = "party", universe = "not_applicable",
        selector = :unique),
    value_group("PartyTwentyEighteenFragmentation",
        "2018 effective party numbers: inverse sum of squared production vote/seat shares",
        :fragmentation, (; election_year = 2018), [
            ("Electoral", :effective_electoral, :decimal2),
            ("Parliamentary", :effective_parliamentary, :decimal2),
        ]; domain = "party", universe = "not_applicable",
        selector = :unique),
    value_group("PartyTwentyTwentyTwoFragmentation",
        "2022 effective party numbers: inverse sum of squared production vote/seat shares",
        :fragmentation, (; election_year = 2022), [
            ("Electoral", :effective_electoral, :decimal2),
            ("Parliamentary", :effective_parliamentary, :decimal2),
        ]; domain = "party", universe = "not_applicable",
        selector = :unique),
]

end
